# Force rebuild: 2025-12-26 09:55
title: Kiệt Nguyễn Blog
description: Trang blog chia sẻ kiến thức về Java và JavaScript.
theme: minima
plugins:
  - jekyll-feed

# Menu yêu cầu
header_pages:
  - index.md
  - profile.md
  - blog.md
  - contact.md